// Generated by gencpp from file kuri_api/VolumeButton.msg
// DO NOT EDIT!


#ifndef KURI_API_MESSAGE_VOLUMEBUTTON_H
#define KURI_API_MESSAGE_VOLUMEBUTTON_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuri_api
{
template <class ContainerAllocator>
struct VolumeButton_
{
  typedef VolumeButton_<ContainerAllocator> Type;

  VolumeButton_()
    : up_button_pressed(false)
    , down_button_pressed(false)  {
    }
  VolumeButton_(const ContainerAllocator& _alloc)
    : up_button_pressed(false)
    , down_button_pressed(false)  {
  (void)_alloc;
    }



   typedef uint8_t _up_button_pressed_type;
  _up_button_pressed_type up_button_pressed;

   typedef uint8_t _down_button_pressed_type;
  _down_button_pressed_type down_button_pressed;





  typedef boost::shared_ptr< ::kuri_api::VolumeButton_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuri_api::VolumeButton_<ContainerAllocator> const> ConstPtr;

}; // struct VolumeButton_

typedef ::kuri_api::VolumeButton_<std::allocator<void> > VolumeButton;

typedef boost::shared_ptr< ::kuri_api::VolumeButton > VolumeButtonPtr;
typedef boost::shared_ptr< ::kuri_api::VolumeButton const> VolumeButtonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuri_api::VolumeButton_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuri_api::VolumeButton_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuri_api::VolumeButton_<ContainerAllocator1> & lhs, const ::kuri_api::VolumeButton_<ContainerAllocator2> & rhs)
{
  return lhs.up_button_pressed == rhs.up_button_pressed &&
    lhs.down_button_pressed == rhs.down_button_pressed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuri_api::VolumeButton_<ContainerAllocator1> & lhs, const ::kuri_api::VolumeButton_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuri_api

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuri_api::VolumeButton_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuri_api::VolumeButton_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuri_api::VolumeButton_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuri_api::VolumeButton_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuri_api::VolumeButton_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuri_api::VolumeButton_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuri_api::VolumeButton_<ContainerAllocator> >
{
  static const char* value()
  {
    return "521894f40e8f5ce718766f39cf828cea";
  }

  static const char* value(const ::kuri_api::VolumeButton_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x521894f40e8f5ce7ULL;
  static const uint64_t static_value2 = 0x18766f39cf828ceaULL;
};

template<class ContainerAllocator>
struct DataType< ::kuri_api::VolumeButton_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuri_api/VolumeButton";
  }

  static const char* value(const ::kuri_api::VolumeButton_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuri_api::VolumeButton_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool up_button_pressed\n"
"bool down_button_pressed\n"
;
  }

  static const char* value(const ::kuri_api::VolumeButton_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuri_api::VolumeButton_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.up_button_pressed);
      stream.next(m.down_button_pressed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VolumeButton_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuri_api::VolumeButton_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuri_api::VolumeButton_<ContainerAllocator>& v)
  {
    s << indent << "up_button_pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.up_button_pressed);
    s << indent << "down_button_pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.down_button_pressed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KURI_API_MESSAGE_VOLUMEBUTTON_H
