; Auto-generated. Do not edit!


(cl:in-package gizmo_msgs-msg)


;//! \htmlinclude CalibrationPathFeedback.msg.html

(cl:defclass <CalibrationPathFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass CalibrationPathFeedback (<CalibrationPathFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CalibrationPathFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CalibrationPathFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gizmo_msgs-msg:<CalibrationPathFeedback> is deprecated: use gizmo_msgs-msg:CalibrationPathFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CalibrationPathFeedback>) ostream)
  "Serializes a message object of type '<CalibrationPathFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CalibrationPathFeedback>) istream)
  "Deserializes a message object of type '<CalibrationPathFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CalibrationPathFeedback>)))
  "Returns string type for a message object of type '<CalibrationPathFeedback>"
  "gizmo_msgs/CalibrationPathFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CalibrationPathFeedback)))
  "Returns string type for a message object of type 'CalibrationPathFeedback"
  "gizmo_msgs/CalibrationPathFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CalibrationPathFeedback>)))
  "Returns md5sum for a message object of type '<CalibrationPathFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CalibrationPathFeedback)))
  "Returns md5sum for a message object of type 'CalibrationPathFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CalibrationPathFeedback>)))
  "Returns full string definition for message of type '<CalibrationPathFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CalibrationPathFeedback)))
  "Returns full string definition for message of type 'CalibrationPathFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CalibrationPathFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CalibrationPathFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CalibrationPathFeedback
))
