(cl:defpackage vision_msgs-msg
  (:use )
  (:export
   "<CLASSIFIEDOBJECT>"
   "CLASSIFIEDOBJECT"
   "<CLASSIFIEDOBJECTS>"
   "CLASSIFIEDOBJECTS"
   "<DETECTEDOBJECTS>"
   "DETECTEDOBJECTS"
   "<FACE>"
   "FACE"
   "<FACEARRAY>"
   "FACEARRAY"
   "<FRAMERESULTS>"
   "FRAMERESULTS"
   "<IMAGECLUSTERING>"
   "IMAGECLUSTERING"
   "<IMAGEQUALITY>"
   "IMAGEQUALITY"
   "<OBJECTFEATURES>"
   "OBJECTFEATURES"
   "<VISIONCMDMSG>"
   "VISIONCMDMSG"
  ))

