(cl:defpackage may_nav_msgs-msg
  (:use )
  (:export
   "<COSTMAP>"
   "COSTMAP"
   "<NAVIGATEACTION>"
   "NAVIGATEACTION"
   "<NAVIGATEACTIONFEEDBACK>"
   "NAVIGATEACTIONFEEDBACK"
   "<NAVIGATEACTIONGOAL>"
   "NAVIGATEACTIONGOAL"
   "<NAVIGATEACTIONRESULT>"
   "NAVIGATEACTIONRESULT"
   "<NAVIGATEFEEDBACK>"
   "NAVIGATEFEEDBACK"
   "<NAVIGATEGOAL>"
   "NAVIGATEGOAL"
   "<NAVIGATERESULT>"
   "NAVIGATERESULT"
   "<SCOREDTRAJECTORIES>"
   "SCOREDTRAJECTORIES"
   "<TRAJECTORY>"
   "TRAJECTORY"
  ))

