(cl:in-package may_nav_msgs-msg)
(cl:export '(TRAJECTORIES-VAL
          TRAJECTORIES
          SCORES-VAL
          SCORES
          PLAN_DISTANCE_SCORES-VAL
          PLAN_DISTANCE_SCORES
          TARGET_DISTANCE_SCORES-VAL
          TARGET_DISTANCE_SCORES
          PLAN_ANGLE_DIFFERENCE_SCORES-VAL
          PLAN_ANGLE_DIFFERENCE_SCORES
          TARGET_ANGLE_DIFFERENCE_SCORES-VAL
          TARGET_ANGLE_DIFFERENCE_SCORES
          OBSTACLE_SCORES-VAL
          OBSTACLE_SCORES
          HEADING_ANGLE_DIFFERENCE_SCORES-VAL
          HEADING_ANGLE_DIFFERENCE_SCORES
          CHOSEN_TRAJECTORY_INDEX-VAL
          CHOSEN_TRAJECTORY_INDEX
))