// Generated by gencpp from file social_sim_ros/PersonEntryArray.msg
// DO NOT EDIT!


#ifndef SOCIAL_SIM_ROS_MESSAGE_PERSONENTRYARRAY_H
#define SOCIAL_SIM_ROS_MESSAGE_PERSONENTRYARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <social_sim_ros/PersonEntry.h>

namespace social_sim_ros
{
template <class ContainerAllocator>
struct PersonEntryArray_
{
  typedef PersonEntryArray_<ContainerAllocator> Type;

  PersonEntryArray_()
    : header()
    , people()  {
    }
  PersonEntryArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , people(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::social_sim_ros::PersonEntry_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::social_sim_ros::PersonEntry_<ContainerAllocator> >> _people_type;
  _people_type people;





  typedef boost::shared_ptr< ::social_sim_ros::PersonEntryArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::social_sim_ros::PersonEntryArray_<ContainerAllocator> const> ConstPtr;

}; // struct PersonEntryArray_

typedef ::social_sim_ros::PersonEntryArray_<std::allocator<void> > PersonEntryArray;

typedef boost::shared_ptr< ::social_sim_ros::PersonEntryArray > PersonEntryArrayPtr;
typedef boost::shared_ptr< ::social_sim_ros::PersonEntryArray const> PersonEntryArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::social_sim_ros::PersonEntryArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::social_sim_ros::PersonEntryArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::social_sim_ros::PersonEntryArray_<ContainerAllocator1> & lhs, const ::social_sim_ros::PersonEntryArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.people == rhs.people;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::social_sim_ros::PersonEntryArray_<ContainerAllocator1> & lhs, const ::social_sim_ros::PersonEntryArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace social_sim_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::social_sim_ros::PersonEntryArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::social_sim_ros::PersonEntryArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::social_sim_ros::PersonEntryArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::social_sim_ros::PersonEntryArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::social_sim_ros::PersonEntryArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::social_sim_ros::PersonEntryArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::social_sim_ros::PersonEntryArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8348034da65c22b0b7c89265fa8ea1ee";
  }

  static const char* value(const ::social_sim_ros::PersonEntryArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8348034da65c22b0ULL;
  static const uint64_t static_value2 = 0xb7c89265fa8ea1eeULL;
};

template<class ContainerAllocator>
struct DataType< ::social_sim_ros::PersonEntryArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "social_sim_ros/PersonEntryArray";
  }

  static const char* value(const ::social_sim_ros::PersonEntryArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::social_sim_ros::PersonEntryArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message defining an array of all people entries\n"
"\n"
"Header          header      # Age of the track\n"
"PersonEntry[]   people      # Array containing the entries for the N tracked persons\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: social_sim_ros/PersonEntry\n"
"# Message defining an entry of a person\n"
"\n"
"Header      header         # Age of the track\n"
"uint64      track_id       # Unique ID for each person\n"
"\n"
"# The following fields are extracted from the Kalman state x and its covariance C\n"
"\n"
"# Pose of the track\n"
"geometry_msgs/Pose      pose\n"
"\n"
"# Velocity of the track\n"
"geometry_msgs/Twist     twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::social_sim_ros::PersonEntryArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::social_sim_ros::PersonEntryArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.people);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PersonEntryArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::social_sim_ros::PersonEntryArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::social_sim_ros::PersonEntryArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "people[]" << std::endl;
    for (size_t i = 0; i < v.people.size(); ++i)
    {
      s << indent << "  people[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::social_sim_ros::PersonEntry_<ContainerAllocator> >::stream(s, indent + "    ", v.people[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOCIAL_SIM_ROS_MESSAGE_PERSONENTRYARRAY_H
