// Generated by gencpp from file gizmo_msgs/CalibrationPathResult.msg
// DO NOT EDIT!


#ifndef GIZMO_MSGS_MESSAGE_CALIBRATIONPATHRESULT_H
#define GIZMO_MSGS_MESSAGE_CALIBRATIONPATHRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gizmo_msgs
{
template <class ContainerAllocator>
struct CalibrationPathResult_
{
  typedef CalibrationPathResult_<ContainerAllocator> Type;

  CalibrationPathResult_()
    : success(false)
    , error()  {
    }
  CalibrationPathResult_(const ContainerAllocator& _alloc)
    : success(false)
    , error(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator> const> ConstPtr;

}; // struct CalibrationPathResult_

typedef ::gizmo_msgs::CalibrationPathResult_<std::allocator<void> > CalibrationPathResult;

typedef boost::shared_ptr< ::gizmo_msgs::CalibrationPathResult > CalibrationPathResultPtr;
typedef boost::shared_ptr< ::gizmo_msgs::CalibrationPathResult const> CalibrationPathResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator1> & lhs, const ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.error == rhs.error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator1> & lhs, const ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gizmo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45872d25d65c97743cc71afc6d4e884d";
  }

  static const char* value(const ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45872d25d65c9774ULL;
  static const uint64_t static_value2 = 0x3cc71afc6d4e884dULL;
};

template<class ContainerAllocator>
struct DataType< ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gizmo_msgs/CalibrationPathResult";
  }

  static const char* value(const ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"#result definition\n"
"bool success\n"
"string error\n"
"\n"
;
  }

  static const char* value(const ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalibrationPathResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gizmo_msgs::CalibrationPathResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GIZMO_MSGS_MESSAGE_CALIBRATIONPATHRESULT_H
