// Generated by gencpp from file gizmo_msgs/ClientWaypoint.msg
// DO NOT EDIT!


#ifndef GIZMO_MSGS_MESSAGE_CLIENTWAYPOINT_H
#define GIZMO_MSGS_MESSAGE_CLIENTWAYPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gizmo_msgs
{
template <class ContainerAllocator>
struct ClientWaypoint_
{
  typedef ClientWaypoint_<ContainerAllocator> Type;

  ClientWaypoint_()
    : request_id()
    , waypoint_uuid()  {
    }
  ClientWaypoint_(const ContainerAllocator& _alloc)
    : request_id(_alloc)
    , waypoint_uuid(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _request_id_type;
  _request_id_type request_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _waypoint_uuid_type;
  _waypoint_uuid_type waypoint_uuid;





  typedef boost::shared_ptr< ::gizmo_msgs::ClientWaypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gizmo_msgs::ClientWaypoint_<ContainerAllocator> const> ConstPtr;

}; // struct ClientWaypoint_

typedef ::gizmo_msgs::ClientWaypoint_<std::allocator<void> > ClientWaypoint;

typedef boost::shared_ptr< ::gizmo_msgs::ClientWaypoint > ClientWaypointPtr;
typedef boost::shared_ptr< ::gizmo_msgs::ClientWaypoint const> ClientWaypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gizmo_msgs::ClientWaypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gizmo_msgs::ClientWaypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gizmo_msgs::ClientWaypoint_<ContainerAllocator1> & lhs, const ::gizmo_msgs::ClientWaypoint_<ContainerAllocator2> & rhs)
{
  return lhs.request_id == rhs.request_id &&
    lhs.waypoint_uuid == rhs.waypoint_uuid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gizmo_msgs::ClientWaypoint_<ContainerAllocator1> & lhs, const ::gizmo_msgs::ClientWaypoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gizmo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gizmo_msgs::ClientWaypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gizmo_msgs::ClientWaypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gizmo_msgs::ClientWaypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gizmo_msgs::ClientWaypoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gizmo_msgs::ClientWaypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gizmo_msgs::ClientWaypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gizmo_msgs::ClientWaypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c9794c65e35c44ec180ec268a6f377c";
  }

  static const char* value(const ::gizmo_msgs::ClientWaypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c9794c65e35c44eULL;
  static const uint64_t static_value2 = 0xc180ec268a6f377cULL;
};

template<class ContainerAllocator>
struct DataType< ::gizmo_msgs::ClientWaypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gizmo_msgs/ClientWaypoint";
  }

  static const char* value(const ::gizmo_msgs::ClientWaypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gizmo_msgs::ClientWaypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string request_id\n"
"string waypoint_uuid\n"
;
  }

  static const char* value(const ::gizmo_msgs::ClientWaypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gizmo_msgs::ClientWaypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request_id);
      stream.next(m.waypoint_uuid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClientWaypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gizmo_msgs::ClientWaypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gizmo_msgs::ClientWaypoint_<ContainerAllocator>& v)
  {
    s << indent << "request_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.request_id);
    s << indent << "waypoint_uuid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.waypoint_uuid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GIZMO_MSGS_MESSAGE_CLIENTWAYPOINT_H
