// Generated by gencpp from file gizmo_msgs/Deafen.msg
// DO NOT EDIT!


#ifndef GIZMO_MSGS_MESSAGE_DEAFEN_H
#define GIZMO_MSGS_MESSAGE_DEAFEN_H

#include <ros/service_traits.h>


#include <gizmo_msgs/DeafenRequest.h>
#include <gizmo_msgs/DeafenResponse.h>


namespace gizmo_msgs
{

struct Deafen
{

typedef DeafenRequest Request;
typedef DeafenResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Deafen
} // namespace gizmo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gizmo_msgs::Deafen > {
  static const char* value()
  {
    return "af6d3a99f0fbeb66d3248fa4b3e675fb";
  }

  static const char* value(const ::gizmo_msgs::Deafen&) { return value(); }
};

template<>
struct DataType< ::gizmo_msgs::Deafen > {
  static const char* value()
  {
    return "gizmo_msgs/Deafen";
  }

  static const char* value(const ::gizmo_msgs::Deafen&) { return value(); }
};


// service_traits::MD5Sum< ::gizmo_msgs::DeafenRequest> should match
// service_traits::MD5Sum< ::gizmo_msgs::Deafen >
template<>
struct MD5Sum< ::gizmo_msgs::DeafenRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gizmo_msgs::Deafen >::value();
  }
  static const char* value(const ::gizmo_msgs::DeafenRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gizmo_msgs::DeafenRequest> should match
// service_traits::DataType< ::gizmo_msgs::Deafen >
template<>
struct DataType< ::gizmo_msgs::DeafenRequest>
{
  static const char* value()
  {
    return DataType< ::gizmo_msgs::Deafen >::value();
  }
  static const char* value(const ::gizmo_msgs::DeafenRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gizmo_msgs::DeafenResponse> should match
// service_traits::MD5Sum< ::gizmo_msgs::Deafen >
template<>
struct MD5Sum< ::gizmo_msgs::DeafenResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gizmo_msgs::Deafen >::value();
  }
  static const char* value(const ::gizmo_msgs::DeafenResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gizmo_msgs::DeafenResponse> should match
// service_traits::DataType< ::gizmo_msgs::Deafen >
template<>
struct DataType< ::gizmo_msgs::DeafenResponse>
{
  static const char* value()
  {
    return DataType< ::gizmo_msgs::Deafen >::value();
  }
  static const char* value(const ::gizmo_msgs::DeafenResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GIZMO_MSGS_MESSAGE_DEAFEN_H
