// Generated by gencpp from file gizmo_msgs/ListFields.msg
// DO NOT EDIT!


#ifndef GIZMO_MSGS_MESSAGE_LISTFIELDS_H
#define GIZMO_MSGS_MESSAGE_LISTFIELDS_H

#include <ros/service_traits.h>


#include <gizmo_msgs/ListFieldsRequest.h>
#include <gizmo_msgs/ListFieldsResponse.h>


namespace gizmo_msgs
{

struct ListFields
{

typedef ListFieldsRequest Request;
typedef ListFieldsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListFields
} // namespace gizmo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gizmo_msgs::ListFields > {
  static const char* value()
  {
    return "83d03de94261ba4e29b909e51c50d482";
  }

  static const char* value(const ::gizmo_msgs::ListFields&) { return value(); }
};

template<>
struct DataType< ::gizmo_msgs::ListFields > {
  static const char* value()
  {
    return "gizmo_msgs/ListFields";
  }

  static const char* value(const ::gizmo_msgs::ListFields&) { return value(); }
};


// service_traits::MD5Sum< ::gizmo_msgs::ListFieldsRequest> should match
// service_traits::MD5Sum< ::gizmo_msgs::ListFields >
template<>
struct MD5Sum< ::gizmo_msgs::ListFieldsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gizmo_msgs::ListFields >::value();
  }
  static const char* value(const ::gizmo_msgs::ListFieldsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gizmo_msgs::ListFieldsRequest> should match
// service_traits::DataType< ::gizmo_msgs::ListFields >
template<>
struct DataType< ::gizmo_msgs::ListFieldsRequest>
{
  static const char* value()
  {
    return DataType< ::gizmo_msgs::ListFields >::value();
  }
  static const char* value(const ::gizmo_msgs::ListFieldsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gizmo_msgs::ListFieldsResponse> should match
// service_traits::MD5Sum< ::gizmo_msgs::ListFields >
template<>
struct MD5Sum< ::gizmo_msgs::ListFieldsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gizmo_msgs::ListFields >::value();
  }
  static const char* value(const ::gizmo_msgs::ListFieldsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gizmo_msgs::ListFieldsResponse> should match
// service_traits::DataType< ::gizmo_msgs::ListFields >
template<>
struct DataType< ::gizmo_msgs::ListFieldsResponse>
{
  static const char* value()
  {
    return DataType< ::gizmo_msgs::ListFields >::value();
  }
  static const char* value(const ::gizmo_msgs::ListFieldsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GIZMO_MSGS_MESSAGE_LISTFIELDS_H
