// Generated by gencpp from file gizmo_msgs/MomentActions.msg
// DO NOT EDIT!


#ifndef GIZMO_MSGS_MESSAGE_MOMENTACTIONS_H
#define GIZMO_MSGS_MESSAGE_MOMENTACTIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <gizmo_msgs/MomentAction.h>

namespace gizmo_msgs
{
template <class ContainerAllocator>
struct MomentActions_
{
  typedef MomentActions_<ContainerAllocator> Type;

  MomentActions_()
    : actions()  {
    }
  MomentActions_(const ContainerAllocator& _alloc)
    : actions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::gizmo_msgs::MomentAction_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::gizmo_msgs::MomentAction_<ContainerAllocator> >> _actions_type;
  _actions_type actions;





  typedef boost::shared_ptr< ::gizmo_msgs::MomentActions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gizmo_msgs::MomentActions_<ContainerAllocator> const> ConstPtr;

}; // struct MomentActions_

typedef ::gizmo_msgs::MomentActions_<std::allocator<void> > MomentActions;

typedef boost::shared_ptr< ::gizmo_msgs::MomentActions > MomentActionsPtr;
typedef boost::shared_ptr< ::gizmo_msgs::MomentActions const> MomentActionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gizmo_msgs::MomentActions_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gizmo_msgs::MomentActions_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gizmo_msgs::MomentActions_<ContainerAllocator1> & lhs, const ::gizmo_msgs::MomentActions_<ContainerAllocator2> & rhs)
{
  return lhs.actions == rhs.actions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gizmo_msgs::MomentActions_<ContainerAllocator1> & lhs, const ::gizmo_msgs::MomentActions_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gizmo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gizmo_msgs::MomentActions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gizmo_msgs::MomentActions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gizmo_msgs::MomentActions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gizmo_msgs::MomentActions_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gizmo_msgs::MomentActions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gizmo_msgs::MomentActions_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gizmo_msgs::MomentActions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d12004285292c1609e1a1a3054cc536";
  }

  static const char* value(const ::gizmo_msgs::MomentActions_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d12004285292c16ULL;
  static const uint64_t static_value2 = 0x09e1a1a3054cc536ULL;
};

template<class ContainerAllocator>
struct DataType< ::gizmo_msgs::MomentActions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gizmo_msgs/MomentActions";
  }

  static const char* value(const ::gizmo_msgs::MomentActions_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gizmo_msgs::MomentActions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MomentAction[] actions\n"
"\n"
"================================================================================\n"
"MSG: gizmo_msgs/MomentAction\n"
"string event\n"
"string uuid\n"
;
  }

  static const char* value(const ::gizmo_msgs::MomentActions_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gizmo_msgs::MomentActions_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MomentActions_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gizmo_msgs::MomentActions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gizmo_msgs::MomentActions_<ContainerAllocator>& v)
  {
    s << indent << "actions[]" << std::endl;
    for (size_t i = 0; i < v.actions.size(); ++i)
    {
      s << indent << "  actions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::gizmo_msgs::MomentAction_<ContainerAllocator> >::stream(s, indent + "    ", v.actions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GIZMO_MSGS_MESSAGE_MOMENTACTIONS_H
