// Generated by gencpp from file gizmo_msgs/RobotPose.msg
// DO NOT EDIT!


#ifndef GIZMO_MSGS_MESSAGE_ROBOTPOSE_H
#define GIZMO_MSGS_MESSAGE_ROBOTPOSE_H

#include <ros/service_traits.h>


#include <gizmo_msgs/RobotPoseRequest.h>
#include <gizmo_msgs/RobotPoseResponse.h>


namespace gizmo_msgs
{

struct RobotPose
{

typedef RobotPoseRequest Request;
typedef RobotPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotPose
} // namespace gizmo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gizmo_msgs::RobotPose > {
  static const char* value()
  {
    return "f192399f711a48924df9a394d37edd67";
  }

  static const char* value(const ::gizmo_msgs::RobotPose&) { return value(); }
};

template<>
struct DataType< ::gizmo_msgs::RobotPose > {
  static const char* value()
  {
    return "gizmo_msgs/RobotPose";
  }

  static const char* value(const ::gizmo_msgs::RobotPose&) { return value(); }
};


// service_traits::MD5Sum< ::gizmo_msgs::RobotPoseRequest> should match
// service_traits::MD5Sum< ::gizmo_msgs::RobotPose >
template<>
struct MD5Sum< ::gizmo_msgs::RobotPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gizmo_msgs::RobotPose >::value();
  }
  static const char* value(const ::gizmo_msgs::RobotPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gizmo_msgs::RobotPoseRequest> should match
// service_traits::DataType< ::gizmo_msgs::RobotPose >
template<>
struct DataType< ::gizmo_msgs::RobotPoseRequest>
{
  static const char* value()
  {
    return DataType< ::gizmo_msgs::RobotPose >::value();
  }
  static const char* value(const ::gizmo_msgs::RobotPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gizmo_msgs::RobotPoseResponse> should match
// service_traits::MD5Sum< ::gizmo_msgs::RobotPose >
template<>
struct MD5Sum< ::gizmo_msgs::RobotPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gizmo_msgs::RobotPose >::value();
  }
  static const char* value(const ::gizmo_msgs::RobotPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gizmo_msgs::RobotPoseResponse> should match
// service_traits::DataType< ::gizmo_msgs::RobotPose >
template<>
struct DataType< ::gizmo_msgs::RobotPoseResponse>
{
  static const char* value()
  {
    return DataType< ::gizmo_msgs::RobotPose >::value();
  }
  static const char* value(const ::gizmo_msgs::RobotPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GIZMO_MSGS_MESSAGE_ROBOTPOSE_H
