// Generated by gencpp from file gizmo_msgs/RomojiFeedback.msg
// DO NOT EDIT!


#ifndef GIZMO_MSGS_MESSAGE_ROMOJIFEEDBACK_H
#define GIZMO_MSGS_MESSAGE_ROMOJIFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gizmo_msgs
{
template <class ContainerAllocator>
struct RomojiFeedback_
{
  typedef RomojiFeedback_<ContainerAllocator> Type;

  RomojiFeedback_()
    : request_id()
    , feedback()  {
    }
  RomojiFeedback_(const ContainerAllocator& _alloc)
    : request_id(_alloc)
    , feedback(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _request_id_type;
  _request_id_type request_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::gizmo_msgs::RomojiFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gizmo_msgs::RomojiFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct RomojiFeedback_

typedef ::gizmo_msgs::RomojiFeedback_<std::allocator<void> > RomojiFeedback;

typedef boost::shared_ptr< ::gizmo_msgs::RomojiFeedback > RomojiFeedbackPtr;
typedef boost::shared_ptr< ::gizmo_msgs::RomojiFeedback const> RomojiFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gizmo_msgs::RomojiFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gizmo_msgs::RomojiFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gizmo_msgs::RomojiFeedback_<ContainerAllocator1> & lhs, const ::gizmo_msgs::RomojiFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.request_id == rhs.request_id &&
    lhs.feedback == rhs.feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gizmo_msgs::RomojiFeedback_<ContainerAllocator1> & lhs, const ::gizmo_msgs::RomojiFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gizmo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gizmo_msgs::RomojiFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gizmo_msgs::RomojiFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gizmo_msgs::RomojiFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gizmo_msgs::RomojiFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gizmo_msgs::RomojiFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gizmo_msgs::RomojiFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gizmo_msgs::RomojiFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "779c10426637afb40e1ff669a0a1211a";
  }

  static const char* value(const ::gizmo_msgs::RomojiFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x779c10426637afb4ULL;
  static const uint64_t static_value2 = 0x0e1ff669a0a1211aULL;
};

template<class ContainerAllocator>
struct DataType< ::gizmo_msgs::RomojiFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gizmo_msgs/RomojiFeedback";
  }

  static const char* value(const ::gizmo_msgs::RomojiFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gizmo_msgs::RomojiFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string request_id\n"
"string feedback\n"
;
  }

  static const char* value(const ::gizmo_msgs::RomojiFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gizmo_msgs::RomojiFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request_id);
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RomojiFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gizmo_msgs::RomojiFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gizmo_msgs::RomojiFeedback_<ContainerAllocator>& v)
  {
    s << indent << "request_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.request_id);
    s << indent << "feedback: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GIZMO_MSGS_MESSAGE_ROMOJIFEEDBACK_H
