// Generated by gencpp from file gizmo_msgs/SetField.msg
// DO NOT EDIT!


#ifndef GIZMO_MSGS_MESSAGE_SETFIELD_H
#define GIZMO_MSGS_MESSAGE_SETFIELD_H

#include <ros/service_traits.h>


#include <gizmo_msgs/SetFieldRequest.h>
#include <gizmo_msgs/SetFieldResponse.h>


namespace gizmo_msgs
{

struct SetField
{

typedef SetFieldRequest Request;
typedef SetFieldResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetField
} // namespace gizmo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gizmo_msgs::SetField > {
  static const char* value()
  {
    return "bed64f0c585e577c90cce651a3e4553f";
  }

  static const char* value(const ::gizmo_msgs::SetField&) { return value(); }
};

template<>
struct DataType< ::gizmo_msgs::SetField > {
  static const char* value()
  {
    return "gizmo_msgs/SetField";
  }

  static const char* value(const ::gizmo_msgs::SetField&) { return value(); }
};


// service_traits::MD5Sum< ::gizmo_msgs::SetFieldRequest> should match
// service_traits::MD5Sum< ::gizmo_msgs::SetField >
template<>
struct MD5Sum< ::gizmo_msgs::SetFieldRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gizmo_msgs::SetField >::value();
  }
  static const char* value(const ::gizmo_msgs::SetFieldRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gizmo_msgs::SetFieldRequest> should match
// service_traits::DataType< ::gizmo_msgs::SetField >
template<>
struct DataType< ::gizmo_msgs::SetFieldRequest>
{
  static const char* value()
  {
    return DataType< ::gizmo_msgs::SetField >::value();
  }
  static const char* value(const ::gizmo_msgs::SetFieldRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gizmo_msgs::SetFieldResponse> should match
// service_traits::MD5Sum< ::gizmo_msgs::SetField >
template<>
struct MD5Sum< ::gizmo_msgs::SetFieldResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gizmo_msgs::SetField >::value();
  }
  static const char* value(const ::gizmo_msgs::SetFieldResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gizmo_msgs::SetFieldResponse> should match
// service_traits::DataType< ::gizmo_msgs::SetField >
template<>
struct DataType< ::gizmo_msgs::SetFieldResponse>
{
  static const char* value()
  {
    return DataType< ::gizmo_msgs::SetField >::value();
  }
  static const char* value(const ::gizmo_msgs::SetFieldResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GIZMO_MSGS_MESSAGE_SETFIELD_H
