// Generated by gencpp from file gizmo_msgs/WakeUp.msg
// DO NOT EDIT!


#ifndef GIZMO_MSGS_MESSAGE_WAKEUP_H
#define GIZMO_MSGS_MESSAGE_WAKEUP_H

#include <ros/service_traits.h>


#include <gizmo_msgs/WakeUpRequest.h>
#include <gizmo_msgs/WakeUpResponse.h>


namespace gizmo_msgs
{

struct WakeUp
{

typedef WakeUpRequest Request;
typedef WakeUpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WakeUp
} // namespace gizmo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gizmo_msgs::WakeUp > {
  static const char* value()
  {
    return "af6d3a99f0fbeb66d3248fa4b3e675fb";
  }

  static const char* value(const ::gizmo_msgs::WakeUp&) { return value(); }
};

template<>
struct DataType< ::gizmo_msgs::WakeUp > {
  static const char* value()
  {
    return "gizmo_msgs/WakeUp";
  }

  static const char* value(const ::gizmo_msgs::WakeUp&) { return value(); }
};


// service_traits::MD5Sum< ::gizmo_msgs::WakeUpRequest> should match
// service_traits::MD5Sum< ::gizmo_msgs::WakeUp >
template<>
struct MD5Sum< ::gizmo_msgs::WakeUpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gizmo_msgs::WakeUp >::value();
  }
  static const char* value(const ::gizmo_msgs::WakeUpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gizmo_msgs::WakeUpRequest> should match
// service_traits::DataType< ::gizmo_msgs::WakeUp >
template<>
struct DataType< ::gizmo_msgs::WakeUpRequest>
{
  static const char* value()
  {
    return DataType< ::gizmo_msgs::WakeUp >::value();
  }
  static const char* value(const ::gizmo_msgs::WakeUpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gizmo_msgs::WakeUpResponse> should match
// service_traits::MD5Sum< ::gizmo_msgs::WakeUp >
template<>
struct MD5Sum< ::gizmo_msgs::WakeUpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gizmo_msgs::WakeUp >::value();
  }
  static const char* value(const ::gizmo_msgs::WakeUpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gizmo_msgs::WakeUpResponse> should match
// service_traits::DataType< ::gizmo_msgs::WakeUp >
template<>
struct DataType< ::gizmo_msgs::WakeUpResponse>
{
  static const char* value()
  {
    return DataType< ::gizmo_msgs::WakeUp >::value();
  }
  static const char* value(const ::gizmo_msgs::WakeUpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GIZMO_MSGS_MESSAGE_WAKEUP_H
