name: p3dx_learning
root: ~/sim_ws

# NOTES:
#  - Hold top left trigger button (1) to enable control
#

windows:
  - dev_abuse:
      layout: tiled
      panes:
        - shell:
        - core:
          - roscore
        - joy:
          - roslaunch --wait social_sim_teleop ps3_teleop_p3dx.launch
        - p2os:
          - roslaunch --wait social_sim_ros p2os_driver.launch
        - zed:
          - roslaunch img_p3dx zed_camera.launch
        - sick_laser:
          - roslaunch --wait sick_scan p3dx_lms100.launch 
        - rviz:
          - rosrun rviz rviz -d $(rospack find img_p3dx)/rviz/p3dx.rviz
        - description:
          - roslaunch --wait p2os_urdf pioneer3dx_urdf.launch
        - map_publisher:
          - rosrun map_server map_server $(rospack find img_p3dx)/maps/lab1.map.yaml
        - amcl:
          - rosrun amcl amcl scan:=scan
        - move_base:
          - roslaunch --wait img_p3dx p3dx_move_base_global_only.launch
        - controller:
          - roslaunch --wait lifecycle_learning p3dx_controller.launch
        - image_republisher:
          -rosrun image_transport republish raw in:=/zed/zed_node/depth/depth_registered compressedDepth out:=/depth
