// Generated by gencpp from file vision_msgs/VisionQuery.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_VISIONQUERY_H
#define VISION_MSGS_MESSAGE_VISIONQUERY_H

#include <ros/service_traits.h>


#include <vision_msgs/VisionQueryRequest.h>
#include <vision_msgs/VisionQueryResponse.h>


namespace vision_msgs
{

struct VisionQuery
{

typedef VisionQueryRequest Request;
typedef VisionQueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VisionQuery
} // namespace vision_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vision_msgs::VisionQuery > {
  static const char* value()
  {
    return "a18a49860895521a1824a72a6363fcaf";
  }

  static const char* value(const ::vision_msgs::VisionQuery&) { return value(); }
};

template<>
struct DataType< ::vision_msgs::VisionQuery > {
  static const char* value()
  {
    return "vision_msgs/VisionQuery";
  }

  static const char* value(const ::vision_msgs::VisionQuery&) { return value(); }
};


// service_traits::MD5Sum< ::vision_msgs::VisionQueryRequest> should match
// service_traits::MD5Sum< ::vision_msgs::VisionQuery >
template<>
struct MD5Sum< ::vision_msgs::VisionQueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vision_msgs::VisionQuery >::value();
  }
  static const char* value(const ::vision_msgs::VisionQueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision_msgs::VisionQueryRequest> should match
// service_traits::DataType< ::vision_msgs::VisionQuery >
template<>
struct DataType< ::vision_msgs::VisionQueryRequest>
{
  static const char* value()
  {
    return DataType< ::vision_msgs::VisionQuery >::value();
  }
  static const char* value(const ::vision_msgs::VisionQueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vision_msgs::VisionQueryResponse> should match
// service_traits::MD5Sum< ::vision_msgs::VisionQuery >
template<>
struct MD5Sum< ::vision_msgs::VisionQueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vision_msgs::VisionQuery >::value();
  }
  static const char* value(const ::vision_msgs::VisionQueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision_msgs::VisionQueryResponse> should match
// service_traits::DataType< ::vision_msgs::VisionQuery >
template<>
struct DataType< ::vision_msgs::VisionQueryResponse>
{
  static const char* value()
  {
    return DataType< ::vision_msgs::VisionQuery >::value();
  }
  static const char* value(const ::vision_msgs::VisionQueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISION_MSGS_MESSAGE_VISIONQUERY_H
