// Generated by gencpp from file vision_msgs/VisionCmdsResponse.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_VISIONCMDSRESPONSE_H
#define VISION_MSGS_MESSAGE_VISIONCMDSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_msgs
{
template <class ContainerAllocator>
struct VisionCmdsResponse_
{
  typedef VisionCmdsResponse_<ContainerAllocator> Type;

  VisionCmdsResponse_()
    : success(false)  {
    }
  VisionCmdsResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::vision_msgs::VisionCmdsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_msgs::VisionCmdsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VisionCmdsResponse_

typedef ::vision_msgs::VisionCmdsResponse_<std::allocator<void> > VisionCmdsResponse;

typedef boost::shared_ptr< ::vision_msgs::VisionCmdsResponse > VisionCmdsResponsePtr;
typedef boost::shared_ptr< ::vision_msgs::VisionCmdsResponse const> VisionCmdsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_msgs::VisionCmdsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_msgs::VisionCmdsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision_msgs::VisionCmdsResponse_<ContainerAllocator1> & lhs, const ::vision_msgs::VisionCmdsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision_msgs::VisionCmdsResponse_<ContainerAllocator1> & lhs, const ::vision_msgs::VisionCmdsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::VisionCmdsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::VisionCmdsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::VisionCmdsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::VisionCmdsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::VisionCmdsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::VisionCmdsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_msgs::VisionCmdsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::vision_msgs::VisionCmdsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_msgs::VisionCmdsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/VisionCmdsResponse";
  }

  static const char* value(const ::vision_msgs::VisionCmdsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_msgs::VisionCmdsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::vision_msgs::VisionCmdsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_msgs::VisionCmdsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisionCmdsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_msgs::VisionCmdsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_msgs::VisionCmdsResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MSGS_MESSAGE_VISIONCMDSRESPONSE_H
