; Auto-generated. Do not edit!


(cl:in-package mobile_base_driver-msg)


;//! \htmlinclude ArcMoveResult.msg.html

(cl:defclass <ArcMoveResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ArcMoveResult (<ArcMoveResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ArcMoveResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ArcMoveResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mobile_base_driver-msg:<ArcMoveResult> is deprecated: use mobile_base_driver-msg:ArcMoveResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ArcMoveResult>) ostream)
  "Serializes a message object of type '<ArcMoveResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ArcMoveResult>) istream)
  "Deserializes a message object of type '<ArcMoveResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ArcMoveResult>)))
  "Returns string type for a message object of type '<ArcMoveResult>"
  "mobile_base_driver/ArcMoveResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ArcMoveResult)))
  "Returns string type for a message object of type 'ArcMoveResult"
  "mobile_base_driver/ArcMoveResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ArcMoveResult>)))
  "Returns md5sum for a message object of type '<ArcMoveResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ArcMoveResult)))
  "Returns md5sum for a message object of type 'ArcMoveResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ArcMoveResult>)))
  "Returns full string definition for message of type '<ArcMoveResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ArcMoveResult)))
  "Returns full string definition for message of type 'ArcMoveResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ArcMoveResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ArcMoveResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ArcMoveResult
))
