(cl:defpackage may_nav_msgs-srv
  (:use )
  (:export
   "GETCOSTMAP"
   "<GETCOSTMAP-REQUEST>"
   "GETCOSTMAP-REQUEST"
   "<GETCOSTMAP-RESPONSE>"
   "GETCOSTMAP-RESPONSE"
   "GETOBSTACLEDIST"
   "<GETOBSTACLEDIST-REQUEST>"
   "GETOBSTACLEDIST-REQUEST"
   "<GETOBSTACLEDIST-RESPONSE>"
   "GETOBSTACLEDIST-RESPONSE"
  ))

