// Generated by gencpp from file may_nav_msgs/GetCostMapResponse.msg
// DO NOT EDIT!


#ifndef MAY_NAV_MSGS_MESSAGE_GETCOSTMAPRESPONSE_H
#define MAY_NAV_MSGS_MESSAGE_GETCOSTMAPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <may_nav_msgs/CostMap.h>

namespace may_nav_msgs
{
template <class ContainerAllocator>
struct GetCostMapResponse_
{
  typedef GetCostMapResponse_<ContainerAllocator> Type;

  GetCostMapResponse_()
    : cost_map()  {
    }
  GetCostMapResponse_(const ContainerAllocator& _alloc)
    : cost_map(_alloc)  {
  (void)_alloc;
    }



   typedef  ::may_nav_msgs::CostMap_<ContainerAllocator>  _cost_map_type;
  _cost_map_type cost_map;





  typedef boost::shared_ptr< ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetCostMapResponse_

typedef ::may_nav_msgs::GetCostMapResponse_<std::allocator<void> > GetCostMapResponse;

typedef boost::shared_ptr< ::may_nav_msgs::GetCostMapResponse > GetCostMapResponsePtr;
typedef boost::shared_ptr< ::may_nav_msgs::GetCostMapResponse const> GetCostMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator1> & lhs, const ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.cost_map == rhs.cost_map;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator1> & lhs, const ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace may_nav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a99a661c9b5861baa696f91f6ec453b2";
  }

  static const char* value(const ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa99a661c9b5861baULL;
  static const uint64_t static_value2 = 0xa696f91f6ec453b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "may_nav_msgs/GetCostMapResponse";
  }

  static const char* value(const ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "may_nav_msgs/CostMap cost_map\n"
"\n"
"================================================================================\n"
"MSG: may_nav_msgs/CostMap\n"
"# This represents a 2-D cost map, in which each\n"
"# cell represents the cost of each position\n"
"# as a float\n"
"\n"
"Header header\n"
"\n"
"# MetaData for the map\n"
"nav_msgs/MapMetaData info\n"
"\n"
"# The cost map data, in row-major order, starting with (0,0).\n"
"# The costs are represented as floats from [0, inf)\n"
"float64[] data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/MapMetaData\n"
"# This hold basic information about the characterists of the OccupancyGrid\n"
"\n"
"# The time at which the map was loaded\n"
"time map_load_time\n"
"# The map resolution [m/cell]\n"
"float32 resolution\n"
"# Map width [cells]\n"
"uint32 width\n"
"# Map height [cells]\n"
"uint32 height\n"
"# The origin of the map [m, m, rad].  This is the real-world pose of the\n"
"# cell (0,0) in the map.\n"
"geometry_msgs/Pose origin\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cost_map);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCostMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::may_nav_msgs::GetCostMapResponse_<ContainerAllocator>& v)
  {
    s << indent << "cost_map: ";
    s << std::endl;
    Printer< ::may_nav_msgs::CostMap_<ContainerAllocator> >::stream(s, indent + "  ", v.cost_map);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAY_NAV_MSGS_MESSAGE_GETCOSTMAPRESPONSE_H
