// Generated by gencpp from file may_nav_msgs/GetObstacleDistRequest.msg
// DO NOT EDIT!


#ifndef MAY_NAV_MSGS_MESSAGE_GETOBSTACLEDISTREQUEST_H
#define MAY_NAV_MSGS_MESSAGE_GETOBSTACLEDISTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace may_nav_msgs
{
template <class ContainerAllocator>
struct GetObstacleDistRequest_
{
  typedef GetObstacleDistRequest_<ContainerAllocator> Type;

  GetObstacleDistRequest_()
    {
    }
  GetObstacleDistRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetObstacleDistRequest_

typedef ::may_nav_msgs::GetObstacleDistRequest_<std::allocator<void> > GetObstacleDistRequest;

typedef boost::shared_ptr< ::may_nav_msgs::GetObstacleDistRequest > GetObstacleDistRequestPtr;
typedef boost::shared_ptr< ::may_nav_msgs::GetObstacleDistRequest const> GetObstacleDistRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace may_nav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "may_nav_msgs/GetObstacleDistRequest";
  }

  static const char* value(const ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetObstacleDistRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::may_nav_msgs::GetObstacleDistRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MAY_NAV_MSGS_MESSAGE_GETOBSTACLEDISTREQUEST_H
