// Generated by gencpp from file may_nav_msgs/NavigateGoal.msg
// DO NOT EDIT!


#ifndef MAY_NAV_MSGS_MESSAGE_NAVIGATEGOAL_H
#define MAY_NAV_MSGS_MESSAGE_NAVIGATEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace may_nav_msgs
{
template <class ContainerAllocator>
struct NavigateGoal_
{
  typedef NavigateGoal_<ContainerAllocator> Type;

  NavigateGoal_()
    : nav_type(0)
    , pose()  {
    }
  NavigateGoal_(const ContainerAllocator& _alloc)
    : nav_type(0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _nav_type_type;
  _nav_type_type nav_type;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(GO_TO_WAYPOINT)
  #undef GO_TO_WAYPOINT
#endif
#if defined(_WIN32) && defined(DRIVE_TO_POINT_IN_IMAGE)
  #undef DRIVE_TO_POINT_IN_IMAGE
#endif
#if defined(_WIN32) && defined(FOLLOW_ME)
  #undef FOLLOW_ME
#endif

  enum {
    GO_TO_WAYPOINT = 0,
    DRIVE_TO_POINT_IN_IMAGE = 1,
    FOLLOW_ME = 2,
  };


  typedef boost::shared_ptr< ::may_nav_msgs::NavigateGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::may_nav_msgs::NavigateGoal_<ContainerAllocator> const> ConstPtr;

}; // struct NavigateGoal_

typedef ::may_nav_msgs::NavigateGoal_<std::allocator<void> > NavigateGoal;

typedef boost::shared_ptr< ::may_nav_msgs::NavigateGoal > NavigateGoalPtr;
typedef boost::shared_ptr< ::may_nav_msgs::NavigateGoal const> NavigateGoalConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::may_nav_msgs::NavigateGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::may_nav_msgs::NavigateGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::may_nav_msgs::NavigateGoal_<ContainerAllocator1> & lhs, const ::may_nav_msgs::NavigateGoal_<ContainerAllocator2> & rhs)
{
  return lhs.nav_type == rhs.nav_type &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::may_nav_msgs::NavigateGoal_<ContainerAllocator1> & lhs, const ::may_nav_msgs::NavigateGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace may_nav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::may_nav_msgs::NavigateGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::may_nav_msgs::NavigateGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::may_nav_msgs::NavigateGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::may_nav_msgs::NavigateGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::may_nav_msgs::NavigateGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::may_nav_msgs::NavigateGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::may_nav_msgs::NavigateGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0717defd8a80a12c8f217581c7cb9ad";
  }

  static const char* value(const ::may_nav_msgs::NavigateGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0717defd8a80a12ULL;
  static const uint64_t static_value2 = 0xc8f217581c7cb9adULL;
};

template<class ContainerAllocator>
struct DataType< ::may_nav_msgs::NavigateGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "may_nav_msgs/NavigateGoal";
  }

  static const char* value(const ::may_nav_msgs::NavigateGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::may_nav_msgs::NavigateGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"byte GO_TO_WAYPOINT=0\n"
"byte DRIVE_TO_POINT_IN_IMAGE=1\n"
"byte FOLLOW_ME=2\n"
"\n"
"byte nav_type\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::may_nav_msgs::NavigateGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::may_nav_msgs::NavigateGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nav_type);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigateGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::may_nav_msgs::NavigateGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::may_nav_msgs::NavigateGoal_<ContainerAllocator>& v)
  {
    s << indent << "nav_type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.nav_type);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAY_NAV_MSGS_MESSAGE_NAVIGATEGOAL_H
