// Generated by gencpp from file mobile_base_driver/Clothesline.msg
// DO NOT EDIT!


#ifndef MOBILE_BASE_DRIVER_MESSAGE_CLOTHESLINE_H
#define MOBILE_BASE_DRIVER_MESSAGE_CLOTHESLINE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mobile_base_driver
{
template <class ContainerAllocator>
struct Clothesline_
{
  typedef Clothesline_<ContainerAllocator> Type;

  Clothesline_()
    : state(0)
    , distance(0.0)  {
    }
  Clothesline_(const ContainerAllocator& _alloc)
    : state(0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;

   typedef float _distance_type;
  _distance_type distance;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(NOTHING)
  #undef NOTHING
#endif
#if defined(_WIN32) && defined(SOMETHING)
  #undef SOMETHING
#endif

  enum {
    NOTHING = 0u,
    SOMETHING = 1u,
  };


  typedef boost::shared_ptr< ::mobile_base_driver::Clothesline_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobile_base_driver::Clothesline_<ContainerAllocator> const> ConstPtr;

}; // struct Clothesline_

typedef ::mobile_base_driver::Clothesline_<std::allocator<void> > Clothesline;

typedef boost::shared_ptr< ::mobile_base_driver::Clothesline > ClotheslinePtr;
typedef boost::shared_ptr< ::mobile_base_driver::Clothesline const> ClotheslineConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobile_base_driver::Clothesline_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobile_base_driver::Clothesline_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobile_base_driver::Clothesline_<ContainerAllocator1> & lhs, const ::mobile_base_driver::Clothesline_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobile_base_driver::Clothesline_<ContainerAllocator1> & lhs, const ::mobile_base_driver::Clothesline_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobile_base_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mobile_base_driver::Clothesline_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_base_driver::Clothesline_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_base_driver::Clothesline_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_base_driver::Clothesline_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_base_driver::Clothesline_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_base_driver::Clothesline_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobile_base_driver::Clothesline_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86c594a65048cb5ab786bd284ae19bfc";
  }

  static const char* value(const ::mobile_base_driver::Clothesline_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86c594a65048cb5aULL;
  static const uint64_t static_value2 = 0xb786bd284ae19bfcULL;
};

template<class ContainerAllocator>
struct DataType< ::mobile_base_driver::Clothesline_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobile_base_driver/Clothesline";
  }

  static const char* value(const ::mobile_base_driver::Clothesline_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobile_base_driver::Clothesline_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# clothesline sensor state\n"
"\n"
"uint8 NOTHING   = 0\n"
"uint8 SOMETHING = 1\n"
"\n"
"uint8   state\n"
"float32 distance\n"
;
  }

  static const char* value(const ::mobile_base_driver::Clothesline_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobile_base_driver::Clothesline_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Clothesline_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobile_base_driver::Clothesline_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobile_base_driver::Clothesline_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILE_BASE_DRIVER_MESSAGE_CLOTHESLINE_H
