// Generated by gencpp from file mobile_base_driver/Sensors.msg
// DO NOT EDIT!


#ifndef MOBILE_BASE_DRIVER_MESSAGE_SENSORS_H
#define MOBILE_BASE_DRIVER_MESSAGE_SENSORS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <mobile_base_driver/Bumper.h>
#include <mobile_base_driver/WheelDrop.h>
#include <mobile_base_driver/Touch.h>

namespace mobile_base_driver
{
template <class ContainerAllocator>
struct Sensors_
{
  typedef Sensors_<ContainerAllocator> Type;

  Sensors_()
    : header()
    , bumper()
    , wheeldrop()
    , touch()  {
    }
  Sensors_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , bumper()
    , wheeldrop()
    , touch(_alloc)  {
  (void)_alloc;
      bumper.assign( ::mobile_base_driver::Bumper_<ContainerAllocator> (_alloc));

      wheeldrop.assign( ::mobile_base_driver::WheelDrop_<ContainerAllocator> (_alloc));
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array< ::mobile_base_driver::Bumper_<ContainerAllocator> , 3>  _bumper_type;
  _bumper_type bumper;

   typedef boost::array< ::mobile_base_driver::WheelDrop_<ContainerAllocator> , 2>  _wheeldrop_type;
  _wheeldrop_type wheeldrop;

   typedef  ::mobile_base_driver::Touch_<ContainerAllocator>  _touch_type;
  _touch_type touch;





  typedef boost::shared_ptr< ::mobile_base_driver::Sensors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobile_base_driver::Sensors_<ContainerAllocator> const> ConstPtr;

}; // struct Sensors_

typedef ::mobile_base_driver::Sensors_<std::allocator<void> > Sensors;

typedef boost::shared_ptr< ::mobile_base_driver::Sensors > SensorsPtr;
typedef boost::shared_ptr< ::mobile_base_driver::Sensors const> SensorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobile_base_driver::Sensors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobile_base_driver::Sensors_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobile_base_driver::Sensors_<ContainerAllocator1> & lhs, const ::mobile_base_driver::Sensors_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.bumper == rhs.bumper &&
    lhs.wheeldrop == rhs.wheeldrop &&
    lhs.touch == rhs.touch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobile_base_driver::Sensors_<ContainerAllocator1> & lhs, const ::mobile_base_driver::Sensors_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobile_base_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mobile_base_driver::Sensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_base_driver::Sensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_base_driver::Sensors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_base_driver::Sensors_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_base_driver::Sensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_base_driver::Sensors_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobile_base_driver::Sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62120da0767c5e0efa3534875705e11a";
  }

  static const char* value(const ::mobile_base_driver::Sensors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62120da0767c5e0eULL;
  static const uint64_t static_value2 = 0xfa3534875705e11aULL;
};

template<class ContainerAllocator>
struct DataType< ::mobile_base_driver::Sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobile_base_driver/Sensors";
  }

  static const char* value(const ::mobile_base_driver::Sensors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobile_base_driver::Sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# sensor state published at a fixed frequency by the driver\n"
"\n"
"Header header\n"
"\n"
"# XXX: sensor indices in their respective arrays does not necessarily\n"
"# reflect what sensor it actually represents\n"
"# Each of these messages has its own internal field for that purpose.\n"
"# Example: check wheeldrop[0].wheel == WheelDrop.RIGHT and do not rely on the 0\n"
"Bumper[3]          bumper\n"
"WheelDrop[2]       wheeldrop\n"
"Touch              touch\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: mobile_base_driver/Bumper\n"
"# Provides a bumper stae\n"
"\n"
"# bumper\n"
"uint8 RIGHT     = 0\n"
"uint8 CENTER    = 1\n"
"uint8 LEFT      = 2\n"
"\n"
"# bumper state\n"
"uint8 RELEASED = 0\n"
"uint8 PRESSED = 1\n"
"\n"
"uint8 bumper\n"
"uint8 state\n"
"\n"
"================================================================================\n"
"MSG: mobile_base_driver/WheelDrop\n"
"# Provides a wheeldrop sensor stae\n"
"\n"
"# wheel\n"
"uint8 RIGHT = 0\n"
"uint8 LEFT  = 1\n"
"\n"
"# wheel state\n"
"uint8 RAISED  = 0\n"
"uint8 DROPPED = 1\n"
"\n"
"uint8 wheel\n"
"uint8 state\n"
"\n"
"================================================================================\n"
"MSG: mobile_base_driver/Touch\n"
"# true means touched\n"
"# [FRONT_LEFT, LEFT, REAR_LEFT, CENTER, FRONT, REAR_RIGHT, RIGHT, FRONT_RIGHT]\n"
"bool[] electrodes\n"
;
  }

  static const char* value(const ::mobile_base_driver::Sensors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobile_base_driver::Sensors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.bumper);
      stream.next(m.wheeldrop);
      stream.next(m.touch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sensors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobile_base_driver::Sensors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobile_base_driver::Sensors_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "bumper[]" << std::endl;
    for (size_t i = 0; i < v.bumper.size(); ++i)
    {
      s << indent << "  bumper[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mobile_base_driver::Bumper_<ContainerAllocator> >::stream(s, indent + "    ", v.bumper[i]);
    }
    s << indent << "wheeldrop[]" << std::endl;
    for (size_t i = 0; i < v.wheeldrop.size(); ++i)
    {
      s << indent << "  wheeldrop[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mobile_base_driver::WheelDrop_<ContainerAllocator> >::stream(s, indent + "    ", v.wheeldrop[i]);
    }
    s << indent << "touch: ";
    s << std::endl;
    Printer< ::mobile_base_driver::Touch_<ContainerAllocator> >::stream(s, indent + "  ", v.touch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILE_BASE_DRIVER_MESSAGE_SENSORS_H
