version: '2.4'
services:
  # builds the code in the workspace
  ros-build:
    build:
      context: ./ros
      args:
        uid: "${USERID}"
        username: "${USERNAME}"
        gid: "${GROUPID}"
        workspacename: "${WORKSPACENAME}"
    image: ros-build:social-sim
    runtime: nvidia
    command: /home/${USERNAME}/${WORKSPACENAME}/docker/scripts/services/build.sh
    user: "${USERID}:${GROUPID}"
    volumes:
      - ../:/home/${USERNAME}/${WORKSPACENAME}
      - ../../.bash_history:/home/${USERNAME}/.bash_history
  # ros master node
  ros-master:
    build:
      context: ./ros
      args:
        uid: "${USERID}"
        username: "${USERNAME}"
        gid: "${GROUPID}"
        workspacename: "${WORKSPACENAME}"
    image: ros-master:social-sim
    networks:
      - default
    ports:
      - "11311:11311"
    runtime: nvidia
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    command: /home/${USERNAME}/${WORKSPACENAME}/docker/scripts/services/master.sh
    user: "${USERID}:${GROUPID}"
    volumes:
      - ../:/home/${USERNAME}/${WORKSPACENAME}
      - ../../.bash_history:/home/${USERNAME}/.bash_history
  # ros-bridge node
  ros-bridge:
    build:
      context: ./ros
      args:
        uid: "${USERID}"
        username: "${USERNAME}"
        gid: "${GROUPID}"
        workspacename: "${WORKSPACENAME}"
    image: ros-bridge:social-sim
    networks:
      - default
    ports:
      - "9090:9090"
    runtime: nvidia
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    command: /home/${USERNAME}/${WORKSPACENAME}/docker/scripts/services/bridge.sh
    user: "${USERID}:${GROUPID}"
    volumes:
      - ../:/home/${USERNAME}/${WORKSPACENAME}
      - ../../.bash_history:/home/${USERNAME}/.bash_history
  # hosts web resources
  nginx:
    depends_on:
      - "ros-bridge"
    build:
      context: ./nginx
      args:
        uid: "${USERID}"
        username: "${USERNAME}"
        gid: "${GROUPID}"
        unityprojectpath: "${UNITYPROJECTPATH}"
        workspacename: "${WORKSPACENAME}"
    image: nginx:social-sim
    networks:
      - default
    ports:
      # host:container
      - "8080:80"
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    command: /home/${USERNAME}/${WORKSPACENAME}/docker/scripts/services/nginx.sh
    user: "${USERID}:${GROUPID}"
    volumes:
      - ../:/home/${USERNAME}/${WORKSPACENAME}
      - ${UNITYPROJECTPATH}/Build:/var/www/html
  # shell node for interactive usage
  ros-shell:
    depends_on:
      - "ros-master"
    build:
      context: ./ros
      args:
        uid: "${USERID}"
        username: "${USERNAME}"
        gid: "${GROUPID}"
        workspacename: "${WORKSPACENAME}"
    image: ros-shell:social-sim
    networks:
      - default
    runtime: nvidia
    environment:
      - "SKIP_BUILD=1"
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "DISPLAY=${DISPLAY}"
    command: /home/${USERNAME}/${WORKSPACENAME}/docker/scripts/services/shell.sh
    user: "${USERID}:${GROUPID}"
    group_add:
      - dialout
    privileged: true
    volumes:
      - ../:/home/${USERNAME}/${WORKSPACENAME}
      - /data:/data
      - /nvme:/nvme
      - ../../.bash_history:/home/${USERNAME}/.bash_history
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev/input/js0:/dev/input/js0:ro
      - /run/udev:/run/udev:ro
    stdin_open: true
    tty: true

networks:
  default:
    driver: bridge
