(cl:defpackage vision_msgs-srv
  (:use )
  (:export
   "VISIONACTIVEMODULES"
   "<VISIONACTIVEMODULES-REQUEST>"
   "VISIONACTIVEMODULES-REQUEST"
   "<VISIONACTIVEMODULES-RESPONSE>"
   "VISIONACTIVEMODULES-RESPONSE"
   "VISIONCMDS"
   "<VISIONCMDS-REQUEST>"
   "VISIONCMDS-REQUEST"
   "<VISIONCMDS-RESPONSE>"
   "VISIONCMDS-RESPONSE"
   "VISIONQUERY"
   "<VISIONQUERY-REQUEST>"
   "VISIONQUERY-REQUEST"
   "<VISIONQUERY-RESPONSE>"
   "VISIONQUERY-RESPONSE"
  ))

