(cl:defpackage mayfield_msgs-srv
  (:use )
  (:export
   "SETSTRING"
   "<SETSTRING-REQUEST>"
   "SETSTRING-REQUEST"
   "<SETSTRING-RESPONSE>"
   "SETSTRING-RESPONSE"
   "STRINGEXCHANGE"
   "<STRINGEXCHANGE-REQUEST>"
   "STRINGEXCHANGE-REQUEST"
   "<STRINGEXCHANGE-RESPONSE>"
   "STRINGEXCHANGE-RESPONSE"
  ))

